apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-platform
  namespace: argocd
spec:
  project: bfsi-platform

  source:
    repoURL: https://github.com/varapalla/istio-bfsi-production-platform.git
    targetRevision: main
    path: phases/phase-01-istio-ambient-installation

  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system

  syncPolicy:
    automated:
      selfHeal: true
      prune: false

    syncOptions:
      - CreateNamespace=true