apiVersion: v1
kind: LimitRange
metadata:
  name: payments-defaults
  namespace: payments
  labels:
    app.kubernetes.io/part-of: istio-bfsi-production-platform
    app.kubernetes.io/component: resource-governance
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: 500m
        memory: 512Mi