apiVersion: v1
kind: Secret
metadata:
  name: bfsi-platform-repository
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  name: bfsi-platform-repository
  project: bfsi-platform
  url: https://github.com/varapalla/istio-bfsi-production-platform.git
  username: "<GITHUB_USERNAME>"
  password: "<GITHUB_TOKEN>"