apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:readonly

  policy.csv: |
    p, role:platform-admin, applications, *, */*, allow
    p, role:platform-admin, projects, get, *, allow
    p, role:platform-admin, repositories, get, *, allow
    p, role:platform-admin, clusters, get, *, allow

    g, argocd-admins, role:platform-admin