configs:
  params:
    server.insecure: "false"

  cm:
    statusbadge.enabled: "true"
    users.anonymous.enabled: "false"
    exec.enabled: "false"

server:
  replicas: 2

repoServer:
  replicas: 2

controller:
  replicas: 1

applicationSet:
  replicaCount: 2