apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: mesh-default
  namespace: istio-system
  labels:
    app.kubernetes.io/part-of: istio-bfsi-production-platform
    app.kubernetes.io/component: security
spec:
  mtls:
    mode: STRICT