apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: bfsi-ingress
  namespace: istio-ingress
  labels:
    app.kubernetes.io/part-of: istio-bfsi-production-platform
    app.kubernetes.io/component: gateway-resilience
spec:
  minAvailable: 1
  selector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: bfsi-ingress